<?php

namespace App\Http\Controllers\System;

use App\Http\Controllers\Controller;
use App\Models\Attendance;
use App\Models\Customer;
use App\Models\Disbursement;
use App\Models\Invoice;
use App\Models\InsuranceApplication;
use App\Models\Lead;
use App\Models\LeadSource;
use App\Models\LoanApplication;
use App\Models\Payment;
use App\Models\Product;
use App\Models\ProductCategory;
use App\Models\User;
use App\Services\ExportService;
use Barryvdh\DomPDF\Facade\Pdf;
use Illuminate\Http\Request;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;
use Illuminate\View\View;

class ReportController extends Controller
{
    public function __construct(protected ExportService $export)
    {
    }

    public function index(Request $request): View
    {
        abort_unless($request->user()->hasPermissionTo('reports.view'), 403);

        return view('reports.index', [
            'reports' => config('loanpro.reports'),
            'products' => Product::query()->active()->ordered()->get(),
            'categories' => ProductCategory::query()->active()->ordered()->get(),
            'employees' => User::query()->where('status', 'active')->orderBy('name')->get(['id', 'name']),
            'lenders' => \App\Models\Lender::query()->active()->ordered()->get(),
        ]);
    }

    public function show(Request $request, string $report): View
    {
        abort_unless($request->user()->hasPermissionTo('reports.view'), 403);
        abort_unless(array_key_exists($report, config('loanpro.reports')), 404);

        [$columns, $rows, $meta] = $this->build($request, $report);

        return view('reports.show', [
            'reportKey' => $report,
            'reportName' => config('loanpro.reports')[$report],
            'columns' => $columns,
            'rows' => $rows,
            'meta' => $meta,
            'filters' => $request->all(),
            'products' => Product::query()->active()->ordered()->get(),
            'categories' => ProductCategory::query()->active()->ordered()->get(),
            'employees' => User::query()->where('status', 'active')->orderBy('name')->get(['id', 'name']),
            'lenders' => \App\Models\Lender::query()->active()->ordered()->get(),
        ]);
    }

    public function export(Request $request, string $report)
    {
        abort_unless($request->user()->hasPermissionTo('reports.export'), 403);

        [$columns, $rows, $meta] = $this->build($request, $report, 5000);

        return $this->export->xlsx(
            $report.'-'.now()->format('Ymd-His').'.xlsx',
            $columns,
            $rows,
            config('loanpro.reports')[$report] ?? 'Report',
            $meta
        );
    }

    public function pdf(Request $request, string $report)
    {
        abort_unless($request->user()->hasPermissionTo('reports.export'), 403);

        [$columns, $rows, $meta] = $this->build($request, $report, 2000);

        $pdf = Pdf::loadView('reports.pdf', [
            'reportName' => config('loanpro.reports')[$report] ?? 'Report',
            'columns' => $columns,
            'rows' => $rows,
            'meta' => $meta,
        ])->setPaper('a4', 'landscape');

        return $pdf->download($report.'-'.now()->format('Ymd-His').'.pdf');
    }

    /**
     * Every report shares the same filter surface: date range, employee,
     * product, category, lender, status and city.
     */
    protected function build(Request $request, string $report, int $limit = 500): array
    {
        $from = $request->filled('from_date') ? Carbon::parse($request->string('from_date')) : now()->startOfMonth();
        $to = $request->filled('to_date') ? Carbon::parse($request->string('to_date')) : now();
        $user = $request->user();

        $meta = [
            'Report' => config('loanpro.reports')[$report] ?? $report,
            'Period' => $from->format('d M Y').' to '.$to->format('d M Y'),
            'Generated By' => $user->name,
            'Generated At' => now()->format('d M Y H:i'),
        ];

        return match ($report) {
            'lead-summary' => [
                ['Lead ID', 'Customer', 'Mobile', 'Category', 'Purpose', 'Amount', 'Source', 'Status', 'Owner', 'Created On'],
                Lead::query()->ownedBy($user)
                    ->dateBetween($from->toDateString(), $to->toDateString())
                    ->when($request->filled('status'), fn ($q) => $q->where('status', $request->string('status')))
                    ->when($request->filled('employee_id'), fn ($q) => $q->where('assigned_to', $request->integer('employee_id')))
                    ->when($request->filled('product_id'), fn ($q) => $q->where('product_id', $request->integer('product_id')))
                    ->when($request->filled('category_id'), fn ($q) => $q->where('product_category_id', $request->integer('category_id')))
                    ->when($request->filled('city'), fn ($q) => $q->whereHas('customer', fn ($c) => $c->where('city', $request->string('city'))))
                    ->with(['customer', 'category', 'subcategory', 'leadStatus', 'assignee', 'source'])
                    ->latest()->limit($limit)->get()
                    ->map(fn (Lead $l) => [
                        $l->lead_code, $l->customer?->name, $l->customer?->mobile, $l->category?->name,
                        $l->subcategory?->name, $l->loan_amount, $l->source?->name,
                        $l->leadStatus?->name, $l->assignee?->name, $l->created_at?->format('d M Y'),
                    ]),
                $meta,
            ],

            'lead-conversion' => [
                ['Stage', 'Leads', 'Conversion %'],
                $this->funnelRows($user, $from, $to),
                $meta,
            ],

            'customer' => [
                ['Customer ID', 'Name', 'Mobile', 'City', 'Occupation', 'Monthly Income', 'KYC', 'Leads', 'Created On'],
                Customer::query()->ownedBy($user)
                    ->dateBetween($from->toDateString(), $to->toDateString())
                    ->when($request->filled('city'), fn ($q) => $q->where('city', $request->string('city')))
                    ->when($request->filled('employee_id'), fn ($q) => $q->where('assigned_employee_id', $request->integer('employee_id')))
                    ->withCount('leads')
                    ->latest()->limit($limit)->get()
                    ->map(fn (Customer $c) => [
                        $c->customer_code, $c->name, $c->mobile, $c->city, $c->occupation,
                        $c->monthly_income, $c->kyc_status, $c->leads_count, $c->created_at?->format('d M Y'),
                    ]),
                $meta,
            ],

            'loan-application' => [
                ['Application ID', 'Customer', 'Category', 'Amount', 'ROI %', 'EMI', 'Tenure', 'Lender', 'Status', 'Created On'],
                LoanApplication::query()->ownedBy($user)
                    ->dateBetween($from->toDateString(), $to->toDateString())
                    ->when($request->filled('status'), fn ($q) => $q->where('status', $request->string('status')))
                    ->when($request->filled('category_id'), fn ($q) => $q->where('product_category_id', $request->integer('category_id')))
                    ->when($request->filled('lender_id'), fn ($q) => $q->where('primary_lender_id', $request->integer('lender_id')))
                    ->when($request->filled('employee_id'), fn ($q) => $q->where('assigned_to', $request->integer('employee_id')))
                    ->with(['customer', 'category', 'lender'])
                    ->latest()->limit($limit)->get()
                    ->map(fn (LoanApplication $a) => [
                        $a->application_code, $a->customer?->name, $a->category?->name, $a->loan_amount,
                        $a->roi, $a->emi, $a->tenure_months, $a->lender?->name,
                        \App\Support\StatusBadge::label($a->status), $a->created_at?->format('d M Y'),
                    ]),
                $meta,
            ],

            'loan-disbursement' => [
                ['Disbursement ID', 'Date', 'Customer', 'Application', 'Lender', 'Approved', 'Fees', 'Net Disbursed', 'Status', 'UTR'],
                Disbursement::query()->ownedBy($user)
                    ->dateBetween($from->toDateString(), $to->toDateString(), 'disbursement_date')
                    ->when($request->filled('status'), fn ($q) => $q->where('status', $request->string('status')))
                    ->when($request->filled('lender_id'), fn ($q) => $q->where('lender_id', $request->integer('lender_id')))
                    ->with(['customer', 'lender', 'application'])
                    ->latest('disbursement_date')->limit($limit)->get()
                    ->map(fn (Disbursement $d) => [
                        $d->disbursement_code, $d->disbursement_date?->format('d M Y'), $d->customer?->name,
                        $d->application?->application_code, $d->lender?->name, $d->approved_amount,
                        $d->processing_fee, $d->net_amount, \App\Support\StatusBadge::label($d->status), $d->utr_number,
                    ]),
                $meta,
            ],

            'insurance' => [
                ['Application ID', 'Customer', 'Insurance Type', 'Plan', 'Sum Assured', 'Premium', 'Insurer', 'Status', 'Policy No'],
                InsuranceApplication::query()->ownedBy($user)
                    ->dateBetween($from->toDateString(), $to->toDateString())
                    ->when($request->filled('status'), fn ($q) => $q->where('status', $request->string('status')))
                    ->with(['customer', 'insuranceType', 'plan', 'insurer'])
                    ->latest()->limit($limit)->get()
                    ->map(fn (InsuranceApplication $i) => [
                        $i->application_code, $i->customer?->name, $i->insuranceType?->name, $i->plan?->name,
                        $i->sum_assured, $i->premium_amount, $i->insurer?->name,
                        \App\Support\StatusBadge::label($i->status), $i->policy_number,
                    ]),
                $meta,
            ],

            'invoice' => [
                ['Invoice No', 'Customer', 'Invoice Date', 'Due Date', 'Total', 'Paid', 'Balance', 'Status'],
                Invoice::query()->ownedBy($user)
                    ->dateBetween($from->toDateString(), $to->toDateString(), 'invoice_date')
                    ->when($request->filled('status'), fn ($q) => $q->where('status', $request->string('status')))
                    ->with('customer')
                    ->latest('invoice_date')->limit($limit)->get()
                    ->map(fn (Invoice $i) => [
                        $i->invoice_number, $i->customer?->name, $i->invoice_date?->format('d M Y'),
                        $i->due_date?->format('d M Y'), $i->total, $i->paid_amount, $i->balance_amount,
                        \App\Support\StatusBadge::label($i->status),
                    ]),
                $meta,
            ],

            'payment-collection' => [
                ['Payment ID', 'Date', 'Customer', 'Invoice', 'Amount', 'Method', 'Reference', 'Status'],
                Payment::query()->ownedBy($user)
                    ->dateBetween($from->toDateString(), $to->toDateString(), 'payment_date')
                    ->when($request->filled('status'), fn ($q) => $q->where('status', $request->string('status')))
                    ->with(['customer', 'paymentMethod', 'invoice'])
                    ->latest('payment_date')->limit($limit)->get()
                    ->map(fn (Payment $p) => [
                        $p->payment_code, $p->payment_date?->format('d M Y'), $p->customer?->name,
                        $p->invoice?->invoice_number, $p->amount, $p->paymentMethod?->name,
                        $p->transaction_id, \App\Support\StatusBadge::label($p->status),
                    ]),
                $meta,
            ],

            'employee-performance' => [
                ['Employee', 'Designation', 'Leads', 'Applications', 'Approved', 'Disbursed Value', 'Collections'],
                $this->employeePerformance($from, $to, $limit),
                $meta,
            ],

            'attendance' => [
                ['Date', 'Employee', 'Code', 'Check In', 'Check Out', 'Hours', 'Status'],
                Attendance::query()
                    ->with(['employee.user'])
                    ->whereBetween('attendance_date', [$from->toDateString(), $to->toDateString()])
                    ->when($request->filled('employee_id'), fn ($q) => $q->where('employee_id', $request->integer('employee_id')))
                    ->when($request->filled('status'), fn ($q) => $q->where('status', $request->string('status')))
                    ->orderByDesc('attendance_date')->limit($limit)->get()
                    ->map(fn (Attendance $a) => [
                        $a->attendance_date?->format('d M Y'), $a->employee?->user?->name, $a->employee?->employee_code,
                        $a->check_in_at?->format('h:i A'), $a->check_out_at?->format('h:i A'),
                        round($a->worked_minutes / 60, 1), $a->status,
                    ]),
                $meta,
            ],

            default => [[], collect(), $meta],
        };
    }

    protected function funnelRows(User $user, Carbon $from, Carbon $to): array
    {
        $base = fn () => Lead::query()->ownedBy($user)->dateBetween($from->toDateString(), $to->toDateString());

        $stages = [
            'Leads Created' => $base()->count(),
            'OTP Verified' => $base()->whereNotNull('otp_verified_at')->count(),
            'Lenders Selected' => $base()->whereHas('lenders')->count(),
            'Applications Created' => LoanApplication::query()->ownedBy($user)->dateBetween($from->toDateString(), $to->toDateString())->count(),
            'Approved' => LoanApplication::query()->ownedBy($user)->whereIn('status', ['approved', 'disbursed'])->count(),
            'Disbursed' => LoanApplication::query()->ownedBy($user)->where('status', 'disbursed')->count(),
        ];

        $first = max(1, array_values($stages)[0]);
        $rows = [];

        foreach ($stages as $stage => $count) {
            $rows[] = [$stage, $count, round(($count / $first) * 100, 1).'%'];
        }

        return $rows;
    }

    protected function employeePerformance(Carbon $from, Carbon $to, int $limit): array
    {
        return User::query()
            ->where('status', 'active')
            ->with(['employee.designation'])
            ->orderBy('name')
            ->limit($limit)
            ->get()
            ->map(fn (User $user) => [
                $user->name,
                $user->designationLabel(),
                Lead::query()->where('assigned_to', $user->id)->dateBetween($from->toDateString(), $to->toDateString())->count(),
                LoanApplication::query()->where('assigned_to', $user->id)->dateBetween($from->toDateString(), $to->toDateString())->count(),
                LoanApplication::query()->where('assigned_to', $user->id)->whereIn('status', ['approved', 'disbursed'])->count(),
                (float) Disbursement::query()->where('created_by', $user->id)->where('status', 'completed')->sum('disbursed_amount'),
                (float) Payment::query()->where('created_by', $user->id)->sum('amount'),
            ])
            ->all();
    }
}
